In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

In [3]:
df = pd.read_csv('Iris.data.csv', header=None, names=names)
X = np.array(df.iloc[:, 0:4])
y = np.array(df['class'])

In [4]:
# split the data into the train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [8]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)

In [9]:
print ('\nModel accuracy score: ', accuracy_score(y_test, pred))
print("\nFrom the test data")
print('Index\tPredicted\t\tActual')
for i in range(len(pred)):
    if pred[i] != y_test[i]:
        print(i, '\t', pred[i], '\t', y_test[i], ' ****')


Model accuracy score:  0.9555555555555556

From the test data
Index	Predicted		Actual
29 	 Iris-versicolor 	 Iris-virginica  ****
43 	 Iris-virginica 	 Iris-versicolor  ****


In [10]:
DataToPredict = np.array([[5.2,3.5,1.4,0.2],[5.7,2.9,3.6,1.3],[5.8,3.0,5.1,1.8]])
pred = knn.predict(DataToPredict)

In [11]:
print("\nPredicted Results")
for i in range(len(pred)):
    print('\t', DataToPredict[i], '\t', pred[i])


Predicted Results
	 [5.2 3.5 1.4 0.2] 	 Iris-setosa
	 [5.7 2.9 3.6 1.3] 	 Iris-versicolor
	 [5.8 3.  5.1 1.8] 	 Iris-virginica


In [9]:
# my hint:
def euclideanDistance(instance1, instance2, noMissingColsIndex):
    distance = 0
    for idx in range(noMissingColsIndex):
        distance += pow((instance1[idx] - instance2[idx]), 2)
    return math.sqrt(distance)

In [10]:
# noMissingColsIndex is a list
def getNeighbors(allInstanceNoMissing, oneInstanceWithMissing, noMissingColsIndex, k):
    distances = []
    for x in range(len(allInstanceNoMissing)):
        dist = euclideanDistance(oneInstanceWithMissing, allInstanceNoMissing[x], noMissingColsIndex)
        distances.append((allInstanceNoMissing[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors